name: PPotionItem
main: pbol377\Main
author: pbol377
version: 1.0.0
api: 
- 3.5.5
- 3.5.6
- 3.5.7
- 3.5.8
- 3.5.9
- 3.6.0
- 3.6.1
- 3.6.2
- 3.9.0
- 4.0.0

commands:
    효과부여:
       description: 들고있는 아이템에 효과를 부여합니다